// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BssUIClient is the client API for BssUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BssUIClient interface {
	// ListOssSpecs returns a list of Operations Support System(s) that can be started through the UI.
	ListOssSpecs(ctx context.Context, in *ListOssSpecsRequest, opts ...grpc.CallOption) (BssUI_ListOssSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type bssUIClient struct {
	cc grpc.ClientConnInterface
}

func NewBssUIClient(cc grpc.ClientConnInterface) BssUIClient {
	return &bssUIClient{cc}
}

func (c *bssUIClient) ListOssSpecs(ctx context.Context, in *ListOssSpecsRequest, opts ...grpc.CallOption) (BssUI_ListOssSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &BssUI_ServiceDesc.Streams[0], "/v1.BssUI/ListOssSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &bssUIListOssSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BssUI_ListOssSpecsClient interface {
	Recv() (*ListOssSpecsResponse, error)
	grpc.ClientStream
}

type bssUIListOssSpecsClient struct {
	grpc.ClientStream
}

func (x *bssUIListOssSpecsClient) Recv() (*ListOssSpecsResponse, error) {
	m := new(ListOssSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bssUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.BssUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BssUIServer is the server API for BssUI service.
// All implementations must embed UnimplementedBssUIServer
// for forward compatibility
type BssUIServer interface {
	// ListOssSpecs returns a list of Operations Support System(s) that can be started through the UI.
	ListOssSpecs(*ListOssSpecsRequest, BssUI_ListOssSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedBssUIServer()
}

// UnimplementedBssUIServer must be embedded to have forward compatible implementations.
type UnimplementedBssUIServer struct {
}

func (UnimplementedBssUIServer) ListOssSpecs(*ListOssSpecsRequest, BssUI_ListOssSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListOssSpecs not implemented")
}
func (UnimplementedBssUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedBssUIServer) mustEmbedUnimplementedBssUIServer() {}

// UnsafeBssUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BssUIServer will
// result in compilation errors.
type UnsafeBssUIServer interface {
	mustEmbedUnimplementedBssUIServer()
}

func RegisterBssUIServer(s grpc.ServiceRegistrar, srv BssUIServer) {
	s.RegisterService(&BssUI_ServiceDesc, srv)
}

func _BssUI_ListOssSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListOssSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BssUIServer).ListOssSpecs(m, &bssUIListOssSpecsServer{stream})
}

type BssUI_ListOssSpecsServer interface {
	Send(*ListOssSpecsResponse) error
	grpc.ServerStream
}

type bssUIListOssSpecsServer struct {
	grpc.ServerStream
}

func (x *bssUIListOssSpecsServer) Send(m *ListOssSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _BssUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BssUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.BssUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BssUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BssUI_ServiceDesc is the grpc.ServiceDesc for BssUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BssUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.BssUI",
	HandlerType: (*BssUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _BssUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListOssSpecs",
			Handler:       _BssUI_ListOssSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bss-ui.proto",
}
